config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'homes#top'
  get '/home/about' => 'homes#about'
  get '/search', to: 'searchs#search'

  resources :users,only: [:show,:index,:edit,:update] do
     get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  resource :relationships, only: [:create, :destroy]
  end

  resources :books do
  resource :favorites, only: [:create, :destroy]
  resources :book_comments, only: [:create, :destroy]
end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user

	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book
  validates :comment, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 has_many :books, dependent: :destroy
  attachment :profile_image, destroy: false
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :followings,through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  def follow(user_id)
      relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
      relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
      followings.include?(user)
  end

  validates :name, uniqueness: true, length: {minimum: 2, maximum: 20}
  validates :introduction, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top,:about]
	before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path(resource)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comment_controller.rb
class BookCommentController < ApplicationController
  
  def create
    book = BookComment.find(params[book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment_book_id = book.id
    comment.save
    redirect_to book_path(book)
  end
  
  
  def destroy
    BookComment.find_by(id: params[:id]).destroy
    redirect_to book_path(params[:book_id])
  end
  
  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
  
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @comment = current_user.book_comments.new(book_comment_params)
    @comment.book_id = @book.id
    @book_comment = BookComment.new
    if @comment.save
     render 'book_comment/create'
    else
     @book_comment = comment
      @books = Book.find(params[:book_id])
      @book = Book.new
      @user = @books.user
     render :'books/show'
    end
  end


  def destroy
    @books = Book.find(params[:book_id])
    BookComment.find_by(id: params[:id]).destroy
    render 'book_comment/destroy'
  end

  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def show
    @book = Book.new
    @books = Book.find(params[:id])
    @user = @books.user
    @book_comment = BookComment.new
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully"
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def edit
   @book = Book.find(params[:id])
    if @book.user == current_user
    render "edit"
    else
    redirect_to books_path
    end
  end


  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end


end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    def create
        current_user.follow(params[:user_id])
        redirect_to request.referer
    end

    def destroy
        current_user.unfollow(params[:user_id])
         redirect_to request.referer
    end

    def followings
        user = User.find(params[:user_id])
        @users = user.followings
    end

    def followers
        user = User.find(params[:user_id])
        @users = user.followers
    end

end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController

  def search
    @model = params["model"]
    @content = params["content"]
    @method = params["method"]
    @record = search_for(@model, @content, @method)
  end

  private
def search_for(model, content, method)
  if model == 'user'
      if method == 'perfect'
        User.where(name: content)
      else
        User.where('name LIKE ?', '%'+content+'%')
      end
  elsif model == 'book'
      if method == 'perfect'
        Book.where(title: content)
      elsif method == 'forward'
        Book.where('title LIKE ?', content+'%')
      elsif method == 'backward'
        Book.where('title LIKE ?', '%'+content)
      else
        Book.where('title LIKE ?', '%'+content+'%')
      end
  end
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
    @users = User.all
  end

  def index
    @book = Book.new
    @books = Book.all
    @users = User.all
    @user = current_user
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
    render "edit"
    else
    redirect_to user_path
    end
  end

  def update
   @books = @user.books
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end



  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comment_helper.rb
module BookCommentHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comment/_comment_count.html.erb
コメント数:<%= book.book_comments.count %>

app/views/book_comment/_form.html.erb
<div>
    <% if book_comment.errors.any? %>
      <h3><%= book_comment.errors.count %>error prohibited this obj from being saved</h3>
  <br>
      <% book_comment.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    <% end %>
    <%= form_with(model:[books, book_comment], remote: true) do |f| %>
    <%= f.text_area :comment,cols:'85',rows:'5' ,placeholder: "コメントをここに" %>
   <br>
    <%= f.submit "送信" %>
  <% end %>
</div>

app/views/book_comment/_index.html.erb
<table>
  <% books.book_comments.each do |book_comment| %>
<tr>
<td>
  <p><%= image_tag('no_image.jpg') %></p>
  <%= link_to book_comment.user.name, user_path(books.user) %>
</td>
<td>
  <%= book_comment.comment %>
</td>
<td>
  <% if book_comment.user == current_user %>
  <div>
  <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true, class: "btn btn-sm btn-danger"  %>
  </div>
  <% end %>
</td>
</tr>
 <% end %>
 </table>

app/views/book_comment/create.js.erb
$(".comment_table").html("<%= j(render 'book_comment/index', books: @book ) %>");
$("#create_btn").html("<%= j(render 'book_comment/form', books: @book, book_comment: @book_comment) %>");
$("textarea").val('');
$(".comment_count").html("<%= j(render 'book_comment/comment_count', book: @book) %>");

app/views/book_comment/destroy.js.erb
$(".comment_table").html("<%= j(render 'book_comment/index', books: @books ) %>");
<!--$("#destroy_btn").html("<%# j(render 'book_comment/index', books: @books) %>");-->
$(".comment_count").html("<%= j(render 'book_comment/comment_count', book: @books) %>");

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit'Create Book', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td>
          <%= link_to attachment_image_tag(book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg",size: "50x50"),user_path(book.user) %>
        </td>
        <td><%= link_to book.title, book_path(book.id) %></td>
        <td><%= book.body %></td>
        <td id="favorite_btn_<%= book.id %>">
          <%= render 'favorites/favorite', book: book %>
        </td>
        <div id="comment_count">
          <%= render 'book_comment/comment_count', book: book %>
        </div>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
     	<h1>Editing Book</h1>
    <%= render 'layouts/errors', obj: @book %>
      <%= form_with model:@book,local:true do |f| %>
  		<div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control book_title' %>
      </div>
      <div class="form-group">
      <%= f.label :opinion %>
      <%= f.text_area :body, class: 'form-control book_body' %>
      </div>
      <div class="form-group">
      <%= f.submit'Update Book', class: 'btn btn-success' %>
      </div>
    <% end %>
  		<%= link_to 'Show', book_path(@book), class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>

  <% if @book.errors.any? %>
  <h3><%= @book.errors.count %>error prohibited this obj from being saved</h3>
  <br>
  <% @book.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
<% end %>

  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info',user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book%>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
  		    <td><%= link_to user_path(@books.user) do %>
            <%= attachment_image_tag(@books.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
            <%= @books.user.name %>
            <% end %>
          </td>
          <td><%= link_to @books.title, book_path(@books) %></td>
          <td><%= @books.body %></td>
          <% if @books.user == current_user %>
          <td><%= link_to 'Edit', edit_book_path(@books), class: "btn btn-sm btn-success edit_book_#{@books.id}" %></td>
          <td><%= link_to 'Destroy', book_path(@books), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@books.id}"%></td>
           <% end %>
          <td id="favorite_btn_<%= @books.id %>">
          <%= render 'favorites/favorite', book: @books %>
          </td>
          <td class="comment_count">
            <%= render 'book_comment/comment_count', book: @books %>
          </td>
          </tr>
          </table>
          <div class="comment_table">
          <%= render 'book_comment/index', books: @books %>
          </div>
         <div id="create_btn">
         <%= render 'book_comment/form', books: @books, book_comment: @book_comment %>
         </div>
    </div>
  </div>
</div>

app/views/favorites/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
<p>
  <%= link_to book_favorites_path(book),method: :delete, remote: true do %>
    <span style="color: red;">♥</span><%= book.favorites.count %>
  <% end %>
</p>
<% else %>
<p>
  <%= link_to book_favorites_path(book),method: :post, remote: true do %>
    ♡<%= book.favorites.count %>
  <% end %>
</p>
<% end %>

app/views/favorites/create.js.erb
$("#favorite_btn_<%= @book.id %>").html("<%= j(render 'favorites/favorite', book: @book) %>");

app/views/favorites/destroy.js.erb
$("#favorite_btn_<%= @book.id %>").html("<%= j(render 'favorites/favorite', book: @book) %>");

app/views/relationships/_follow_list.html.erb
<% if users.exists? %>
    <% users.each do |user| %>
      <table class='table'>
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
            <td><%= user.name %></td>
            <td>フォロー数:<%= user.followings.count %></td>
             <td>フォロワー数:<%= user.followers.count %></td>
             <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
          </tr>
        </tbody>
      </table>
    <% end %>
  <% else %>
    <p>ユーザーはいません</p>
  <% end %>

app/views/relationships/followers.html.erb
<h2>Follower Users</h2>
  <%= render 'relationships/follow_list', users: @users %>

app/views/relationships/followings.html.erb
<h2>Follow Users</h2>
  <%= render 'relationships/follow_list', users: @users %>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>フォロー数:<%= user.followings.count %></td>
      　<td>フォロワー数:<%= user.followers.count %></td>
      　<td>
      　  <% if current_user.following?(user) %>
            <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
         <% else %>
            <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
         <% end %>
      　</td>
      　<td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count, user_followings_path(user.id) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followers.count, user_followers_path(user.id) %></th>
  </tr>
</table>

<div class='row'>
  <% if current_user == user %>
   <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
  <% else %>
  　　 <% if current_user.following?(user) %>
            <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: 'btn btn-info' %>
         <% else %>
            <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: 'btn btn-success' %>
      <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>

    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% if @book.errors.any? %>
 <h3><%= @book.errors.count %>error prohibited this obj from being saved</h3>
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
        <h2>User info</h2>
        <%= render 'users/info', user: current_user %>
        <h2 class="mt-3">New book</h2>
        <%= render 'books/form', book: @book %>
    </div>
        <div class='col-md-8 offset-md-1'>
        <h2>Users</h2>
        <%= render 'users/index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info' ,user: @user%>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>